Add ability to filter playlists by rating
strawberrymusicplayer/strawberry pull request #1212
Opened 2023-06-06 20:47 UTC by Dakes

This adds the ability to filter your playlists by rating in two different ways. 
For example you can filter by 0-5 Stars like this:
`rating:5` `rating:>=3` `rating:!=0`
Or use float values from 0-1 with a prefixed "f":
`rating:f1` `rating:>0.5`

The implementation got a little messy, unfortunately. But it works.

2023-06-07 15:08 UTC, jonaski requested changes
Thanks, could you squash the 2 correction commits into the first one, and if you rebase with master it should also fix the CI issue.

2023-06-07 21:04 UTC, Dakes commented
I think it is looking good now. ✌️

2023-06-09 19:31 UTC, jonaski approved these changes

2023-06-09 19:31 UTC, merged

2023-06-09 19:50 UTC, Dakes commented
Thank you. I appreciate your work. Have a nice day.