Mark Subsonic MD5 authentication as recommended
strawberrymusicplayer/strawberry pull request #1361
Opened 2024-01-15 23:00 UTC by cquike

This simple MR just marks the MD5 authentication method for subsonic as recommended when editing the settings of subsonic.

2024-01-15 23:42 UTC, cquike commented
The reasoning for this is that the Hex authentication method is the legacy one.
From the subsonic page http://www.subsonic.org/pages/api.jsp :
"The password, either in clear text or hex-encoded with a "enc:" prefix. Since [1.13.0](http://www.subsonic.org/pages/api.jsp#versions) this should only be used for testing purposes."

2024-01-19 22:45 UTC, jonaski requested changes
Please change the commit message so it's prefixed with the class.:
ie.: `SubsonicSettingsPage: Add recommended to MD5 option`

2024-01-21 02:55 UTC, cquike commented
> Please change the commit message so it's prefixed with the class.: ie.: `SubsonicSettingsPage: Add recommended to MD5 option`

Done

2024-01-21 03:01 UTC, jonaski approved these changes

2024-01-21 03:25 UTC, merged