Network Remote
strawberrymusicplayer/strawberry pull request #1398
Opened 2024-03-14 00:36 UTC by poldi171254

The one thing I'm missing in Strawberry is a Remote capability.
I have over 1000 CD, collected over many years, and as we all know, not every song on every CD is great.
In Clementine, if I didn't like something I heard while I was away from the PC/Music System, I could just go Next.

I have added a basic Remote capability to Strawberry 

- The functionality is very basic and not like Clementine (no downloads, playlist changes, etc); all you can do is Play, Pause, Next Previous, Stop, Finish
- Both Strawberry and the Remote were built in Qt Creator; not sure if command line works.
- I've created a Remote Client for testing which can be built from git@github.com:poldi171254/StrawberryRemote.git
- This is a first draft and will obviously need more work

Thanks,
Leo

2024-03-14 04:30 UTC, poldi171254 commented
Just realized I forgot instruction on how to use/enable this.
There is a new settings item, similar to Clementine, that allows the config for the remote

2024-04-16 05:48 UTC, poldi171254 commented
I'd appreciate if somebody could explain why the Ubuntu build fails

2024-04-20 23:19 UTC, jonaski commented
> I'd appreciate if somebody could explain why the Ubuntu build fails

`QAbstractSocket::errorOccurred` was introduced in Qt 5.15, while Ubuntu Focal has Qt 5.12.

For now we still support building with Qt 5, so strawberry can still be supported on LTS distros, but we should probably drop it in not to long future. Qt 5 is already in closed branches for commercial customers and it's hard to know what the "5.15" that distros ship actually is anymore since KDE actually do their own thing with it.

2024-04-22 01:42 UTC, poldi171254 commented
Ubuntu 24.04 LTS release is planned for April 25, so I guesss we can check this then

2024-05-09 11:18 UTC, CAPSLOCK2000 commented
I got it to compile and run on Debian after manually replacing the contents of 3rdparty/kdsingleapplication with a complete copy of https://github.com/KDAB/KDSingleApplication. The copy of KDSingleApplication in Debian is to old an Ubuntu probably has the same problem.


However I cannot find  the github.com:poldi171254/StrawberryRemote.git repository so I can't really test it. 

I tried to use it with code written for clementine remote (without any recompling for Strawberry). It does connect but is unable to parse the messages from the server, probably due to incompatible protobuf message formats. More or less as expected.

FWIW, the code compiled cleanly and Strawberry works fine with the remote code enabled.

2024-05-10 00:36 UTC, poldi171254 commented
Thanks for your feedback. I didn't worry about the KDSingleApplication while the remote code was still in development.
The code for the remote is 
for ssh
git@github.com:poldi171254/StrawberryRemote.git
for https
https://github.com/poldi171254/StrawberryRemote.git

2024-05-14 14:58 UTC, CAPSLOCK2000 commented
On 5/10/24 02:36, Poldi wrote:
> Thanks for your feedback. I didn't worry about the KDSingleApplication while the remote code was 
> still in development.
> The code for the remote is
> for ssh
> ***@***.*** ***@***.***>:poldi171254/StrawberryRemote.git
> for https
> https://github.com/poldi171254/StrawberryRemote.git 
> <https://github.com/poldi171254/StrawberryRemote.git>

Hi Poldi,
I cannot access the repo for the rmeote:

https://github.com/poldi171254/StrawberryRemote -> 404

$ git clone ***@***.***/poldi171254/StrawberryRemote.git
Cloning into 'StrawberryRemote'...
...
ERROR: Repository not found.
fatal: Could not read from remote repository.

Is it perhaps a private repo?

-- 
Casper Gielen

2025-01-09 17:59 UTC, DarthGandalf commented
@poldi171254 probably meant https://github.com/poldi171254/Strawberry-Remote-Android instead?

2025-01-13 04:22 UTC, poldi171254 commented
> @poldi171254 probably meant https://github.com/poldi171254/Strawberry-Remote-Android instead?

I'm still working on the Android Remote.

The linux remote is/should be available via ssh
git@github.com:poldi171254/StrawberryRemote.git

or https
https://github.com/poldi171254/StrawberryRemote.git

2025-02-07 05:12 UTC, poldi171254 commented
I've now completed a basic remote for Android.
Let me knwo if you are interested to try

2025-03-05 20:40 UTC, jonaski requested changes
If #1688 replaces this, then this should be closed, it's confusing that there are 2 PR's for the same feature from 2 different users.

- Please rebase this with master and squash any commits that are corrections to the previous commits.
- The formatting of the code is inconsistent with the codebase, please use 2 spaces for indent everywhere, curly brace on the same line as the function declaration, snake case for variable names everywhere. Consider running it through clang-format to fix some of it (set DisableFormat to false in .clang-format), but only run it on the new code.

2025-03-05 22:24 UTC, closed without merging