Add volume increment setting
strawberrymusicplayer/strawberry pull request #1452
Opened 2024-06-03 17:49 UTC by jjmith

2024-06-04 20:51 UTC, jonaski requested changes
Thanks, could you add back the removed newline and squash the new commit and I'll merge this.

2024-06-04 20:51 UTC, jonaski commented on src/core/player.cpp
> -
nitpick: don't remove newline here.

2024-06-05 17:34 UTC, jjmith commented
Thanks! I think it should be fixed now.

2024-06-06 19:52 UTC, jonaski approved these changes

2024-06-06 19:53 UTC, merged