Re-enable progress on system tray icon
strawberrymusicplayer/strawberry pull request #578
Opened 2020-11-03 00:06 UTC by yavuzmert

#577

2020-11-03 17:03 UTC, jonaski requested changes
It would be nice if you could make a setting for this in the top options of the behavior settings (settings/appearancesettingspage)

2020-11-03 17:03 UTC, jonaski commented on src/core/qtsystemtrayicon.cpp
> +  QIcon theme_icon_grey =
One line please

2020-11-03 17:03 UTC, jonaski commented on src/core/qtsystemtrayicon.cpp
> +  if (! theme_icon_grey.isNull()) {
remove space after !

2020-11-03 21:48 UTC, yavuzmert commented
Hi Jonas, 
Setting and icon progress seem to work - at least on my system :)
I put the checkbox at the bottom of appearance settings, later i saw that you said top of the page. I think bottom is alright but you may reorganize it and put wherever you see appropriate.

2020-11-03 22:27 UTC, jonaski requested changes

2020-11-03 22:27 UTC, jonaski commented on src/core/systemtrayicon.cpp
> +  bool trayicon_progress = s.value(AppearanceSettingsPage::kTrayIconProgress, false).toBool();
Move this to MainWindow::ReloadSettings() so we don't reload the setting each time the icon is painted.
Then add a public method in SystemTrayIcon to call when the setting is reloaded.

2020-11-03 22:27 UTC, jonaski commented on src/settings/appearancesettingspage.cpp
> +#if !defined(Q_OS_WIN)
Windows uses QSystemTrayIcon  too so this isn't needed.

2020-11-03 23:35 UTC, jonaski commented
Sorry I meant behavior settings, settings/behavioursettingspage. I think it makes more sense since that's where the system tray icon options are.

2020-11-04 00:38 UTC, yavuzmert commented
Alright I moved it to behavioursettingspage, I set it enabled when tray icon is checked. 
But only problem I see is, on MacOs, tray icon settings are hidden.
We can show its checkbox also on MacOs although "Show system tray icon" checkbox is hidden, but then we must set its label which makes sense all platforms (maybe "show progress on icon" instead of "show progress on system tray icon")

2020-11-04 16:50 UTC, jonaski commented
The track progress doesn't work on macOS so you can just exclude that option. It's not really a system tray icon on mac at all, it's just the context menu on the dock.

2020-11-04 16:56 UTC, jonaski requested changes

2020-11-04 16:56 UTC, jonaski commented on src/core/mainwindow.cpp
> +  bool trayicon_progress = s.value(AppearanceSettingsPage::kTrayIconProgress, false).toBool();
Move to behavioursettings

2020-11-04 20:00 UTC, jonaski approved these changes

2020-11-04 20:01 UTC, merged