add CLI play-playlist option, to play given playlist name.
strawberrymusicplayer/strawberry pull request #608
Opened 2020-12-01 20:50 UTC by NicolasToussaint

Adding a command line option to start playing the playlist given as argument.

I reused the command line argument playlist_name_ from the create_playlist option.

2020-12-03 18:26 UTC, jonaski requested changes

2020-12-03 18:26 UTC, jonaski commented on src/core/mainwindow.cpp
> +      } else {
}
else {

2020-12-03 18:26 UTC, jonaski commented on src/core/player.cpp
> +void Player::PlayPlaylistInternal(Engine::TrackChangeFlags change,
One line

2020-12-03 18:26 UTC, jonaski commented on src/core/player.cpp
> +void Player::PlayPlaylist(const QString& playlistName) {
const QString &playlist_name

2020-12-03 18:26 UTC, jonaski commented on src/core/player.cpp
> +  if (playlist == NULL) {
nullptr

2020-12-03 18:26 UTC, jonaski commented on src/core/player.cpp
> +  Playlist* playlist = nullptr;
Playlist *playlist = nullptr;

2020-12-03 18:26 UTC, jonaski commented on src/core/player.cpp
> +                                  const QString& playlistName) {
const QString &playlist_name

2020-12-03 18:26 UTC, jonaski commented on src/core/player.h
> +  void PlayPlaylistInternal(Engine::TrackChangeFlags, const Playlist::AutoScroll autoscroll, const QString& playlistName);
const QString &playlist_name

2020-12-04 18:08 UTC, merged

2020-12-04 18:08 UTC, jonaski commented
Thanks!

2020-12-06 19:27 UTC, NicolasToussaint commented
My pleasure, thanks for the great work !