Use optional to fix song fields that were positive or -1
strawberrymusicplayer/strawberry pull request #765
Opened 2021-09-12 22:06 UTC by EmmanuelMess

2021-09-13 19:05 UTC, jonaski requested changes

2021-09-13 19:05 UTC, jonaski commented on src/core/song.cpp
> +  if(d->track_) pb->set_track(d->track_.value());
Please follow the code-style here and all similar lines, space between if and parentheses.
`if (d->track_) pb->set_track(d->track_.value());`

2021-09-13 19:05 UTC, jonaski commented on src/core/song.cpp
> +  } else {
```
}
else {
```
for consistency with the code-style.

2021-09-14 00:47 UTC, EmmanuelMess commented
This should also fix the regression with unknown length songs.

2021-09-14 20:27 UTC, jonaski commented
This might be a good idea, but require a lot of testing.
With these changes 13 unit tests fail:
```

[  FAILED  ] SingleSong.TestUrls (5 ms)
[----------] 12 tests from SingleSong (67 ms total)

[----------] Global test environment tear-down
[==========] 17 tests from 2 test suites ran. (98 ms total)
[  PASSED  ] 4 tests.
[  FAILED  ] 13 tests, listed below:
[  FAILED  ] CollectionBackendTest.AddInvalidSong
[  FAILED  ] SingleSong.GetSongWithNoAlbum
[  FAILED  ] SingleSong.GetAllArtists
[  FAILED  ] SingleSong.GetAllAlbums
[  FAILED  ] SingleSong.GetAlbumsByArtist
[  FAILED  ] SingleSong.GetAlbumArt
[  FAILED  ] SingleSong.GetSongs
[  FAILED  ] SingleSong.GetSongById
[  FAILED  ] SingleSong.FindSongsInDirectory
[  FAILED  ] SingleSong.UpdateSong
[  FAILED  ] SingleSong.DeleteSongs
[  FAILED  ] SingleSong.MarkSongsUnavailable
[  FAILED  ] SingleSong.TestUrls

13 FAILED TESTS

```

2021-09-14 20:37 UTC, jonaski commented
It also crashes:

```
22:34:59.644 DEBUG PlaylistBackend:336              Saving playlist 4
22:34:59.645 WARN  ScopedTransaction:35             Rolling back transaction
22:34:59.645 WARN  unknown                          Qt has caught an exception thrown from an event handler. Throwing 
22:34:59.645 WARN  unknown                          exceptions from an event handler is not supported in Qt. 
22:34:59.645 WARN  unknown                          You must not let any exception whatsoever propagate through Qt code. 
22:34:59.645 WARN  unknown                          If that is not possible, in Qt 5 you must at least reimplement 
22:34:59.645 WARN  unknown                          QCoreApplication::notify() and catch all exceptions there. 
22:34:59.645 WARN  unknown                           
terminate called after throwing an instance of 'std::bad_optional_access'
  what():  bad optional access
Aborted (core dumped)
```

2021-09-19 13:17 UTC, EmmanuelMess commented
@jonaski the only places where bad_optional_access can occur is when accessing id, this is a special case, because once it is set it should not be unset again, but I must have missed the correct program flow where in the execution the id is set and left too many `id().value()` in code, I would replace all of these with value_or(-1), this however has the problem of being equivalent to `static_cast<uint>(-1)` in cases where id is empty. What is the maximum id feasible?

2021-09-19 14:28 UTC, jonaski commented
I think uint is fine, but we need to check everywhere that id is actual set before using value().

2021-09-24 01:08 UTC, EmmanuelMess commented
I will try to fix these in multiple PRs.

2021-09-24 01:08 UTC, closed without merging