Added: Import_Clementine_to_Strawberry.sh
strawberrymusicplayer/strawberry pull request #838
Opened 2021-11-26 23:03 UTC by vazhnov

Based on SQL commands from
https://github.com/strawberrymusicplayer/strawberry/wiki/Import-collection-library-and-playlists-data-from-Clementine

Script works in Gentoo.

* I'm not sure about correct path to put this script in.
* Please check English grammar.

2021-11-27 11:45 UTC, vazhnov commented
These are no need in this script, I can remove them:
```shell
set -o pipefail
shopt -s dotglob
```

2021-11-27 11:56 UTC, vazhnov commented
TODO: update wiki page when this will be merged.

2021-11-27 17:08 UTC, jonaski commented
Thanks. Look good to me, but we should simplify the name of the script. I suggest: `import-from-clementine.sh`

2021-11-27 17:54 UTC, jonaski requested changes

2021-11-27 17:54 UTC, jonaski commented on dist/scripts/Import_Clementine_to_Strawberry.sh
> +echo 'This scipt will **delete all information** from Strawberry database!'
script

2021-11-27 17:54 UTC, jonaski commented on dist/scripts/Import_Clementine_to_Strawberry.sh
> +test -f "$FILE_SRC" || { echo "No file: $FILE_SRC"; exit 1; }
No such file:

2021-11-28 12:14 UTC, jonaski approved these changes

2021-11-28 12:15 UTC, closed without merging