Add "save all playlist" feature
strawberrymusicplayer/strawberry pull request #915
Opened 2022-03-13 12:07 UTC by renn0xtek9

This adds a feature that will save all playlists to m3u in `/home/foo/Playlists` with relative path to the songs. 
This is very usefull if you want to copy paste all you music to e.g. you phone without loosing your playlists.

2022-03-13 16:05 UTC, jonaski requested changes
Please remove all the formatting changes.
Splitting single line if statements is OK with me (easier to debug), but needs to use brackets and be separate PR

2022-03-13 16:05 UTC, jonaski commented on src/core/mainwindow.cpp
> +#  ifndef Q_OS_WIN
Please remove all the formatting changes.

2022-03-13 16:05 UTC, jonaski commented on src/core/mainwindow.cpp
> +  ui_->action_next_playlist->setShortcuts(QList<QKeySequence>() << QKeySequence::fromString("Ctrl+Tab") << QKeySequence::fromString("Ctrl+PgDown"));
This formatting change is correct but needs to be a separate PR.

2022-03-21 21:07 UTC, jonaski requested changes

2022-03-21 21:07 UTC, jonaski commented on src/playlist/playlistmanager.cpp
> +bool PlaylistManager::CreateAPlaylistsDirectory(const QString playlist_folder_path) {
Why isn't this const reference?

2022-03-21 21:07 UTC, jonaski commented on src/playlist/playlistmanager.cpp
> +    QString playlist_folder_path = QDir::home().path() + QDir::separator() + "Playlists";
I think we should show a select folder dialog instead of hard-code the path like this.

2022-03-21 21:07 UTC, jonaski commented on src/playlist/playlistmanager.cpp
> +  for (const auto playlist : GetAllPlaylists()) {
Please use `Playlist *playlist` instead of auto

2022-03-21 21:07 UTC, jonaski commented on src/playlist/playlistmanager.cpp
> +  if (! success) {
```suggestion
  if (!success) {
```

2022-03-21 21:07 UTC, jonaski commented on src/playlist/playlistmanager.cpp
> -
Remove

2022-03-21 21:07 UTC, jonaski commented on src/playlist/playlistmanager.cpp
> +
Remove

2022-03-21 21:07 UTC, jonaski commented on src/playlist/playlistmanager.cpp
> +
Remove

2022-03-21 21:07 UTC, jonaski commented on src/playlist/playlistmanager.cpp
> +
Remove

2022-03-21 21:07 UTC, jonaski commented on src/playlist/playlistmanager.cpp
> +
Remove

2022-03-21 21:07 UTC, jonaski commented on src/playlist/playlistmanager.h
> +  bool CreateAPlaylistsDirectory(const QString playlist_folder_path);
const reference

2022-03-21 21:07 UTC, jonaski commented on src/playlist/playlistcontainer.cpp
> +
Remove

2022-03-21 21:07 UTC, jonaski commented on src/playlist/playlistmanager.cpp
>  }
Remove

2022-03-21 21:07 UTC, jonaski commented on src/playlist/playlistmanager.cpp
> +void PlaylistManager::SaveAllPlaylists() {
Empty line after `{`

2022-03-23 22:16 UTC, renn0xtek9 commented
We shoud focus less on formatting and more and code and testing... 
There is `PlaylistBackend::Playlist`, and `Playlist` in playlist.h < Are we sure that we need two representation of the same thing? 
`playlistmanager::GetAllPlaylist()` will only return the currently opened playlsit while `playlist_backend::GetAllPlaylist`  return all  playlist. Sadly `GetPlaylistName(id)` will return empty names(!) .
I was searching for unit tests on those but could find any.
I would like to help refactor and test it, but we need to increase the pace at which we get things merge ...

2022-03-24 19:14 UTC, jonaski commented
> We shoud focus less on formatting and more and code and testing... There is `PlaylistBackend::Playlist`, and `Playlist` in playlist.h < Are we sure that we need two representation of the same thing? `playlistmanager::GetAllPlaylist()` will only return the currently opened playlsit while `playlist_backend::GetAllPlaylist` return all playlist. Sadly `GetPlaylistName(id)` will return empty names(!) (execpt for the playlist currently in creation) I was searching for unit tests on those but could find any. I would like to help refactor and test it, but we need to increase the pace at which we get things merge ... ![image](https://user-images.githubusercontent.com/12097757/159805754-7cf0d57b-0f41-49ee-b494-f8279ec78a4b.png)

Please try to follow the same code style.

`PlaylistBackend::Playlist` is a simple structure that holds the data saved to DB for each playlist. `Playlist` is a model for each playlists that is open.

2022-03-24 21:29 UTC, renn0xtek9 commented
Works and formatted. :+1:

2022-03-26 21:47 UTC, jonaski reviewed
I manually re-based this to squash the commits and fix the remaining formatting.

See https://github.com/strawberrymusicplayer/strawberry/commit/962b52bd5b8a45f854bca064c6934d57593acfb4

If you want to save all playlists including those that are not open, it needs to be done in the backend with signals/slots as it would block the UI otherwise.

2022-03-26 21:47 UTC, jonaski commented on src/playlist/playlistmanager.cpp
> +#include <QStandardPaths>
This isn't used

2022-03-26 21:47 UTC, jonaski commented on src/playlist/playlistmanager.cpp
> +  QString playlist_folder_path = QFileDialog::getExistingDirectory(nullptr, tr("Open Directory"),QDir::home().path(),QFileDialog::ShowDirsOnly| QFileDialog::DontResolveSymlinks);
QDir::homePath() can be used.

2022-03-26 21:47 UTC, jonaski commented on src/playlist/playlistmanager.cpp
> +    Save(id, playlist_file_name, Playlist::Path_Relative);
` QFileDialog::getExistingDirectory()` returns absolute paths

2022-03-26 21:47 UTC, jonaski commented on src/playlist/playlistmanager.cpp
> +  if (!CreateAPlaylistsDirectory(playlist_folder_path)) {
`QFileDialog::getExistingDirectory` returns an existing directory, so this should be unnecessary.

2022-03-26 21:47 UTC, jonaski commented on src/playlist/playlistcontainer.cpp
> +void PlaylistContainer::SaveAllPlaylists() {
This slot function is unnecessary as you can connect directly to `PlaylistManager::SaveAllPlaylists`

2022-03-26 21:47 UTC, jonaski commented on src/playlist/playlistmanager.cpp
> +  for (const PlaylistBackend::Playlist& playlist : playlist_backend_->GetAllPlaylists()) {
We should probably do this in the playlist backend.

2022-03-26 21:47 UTC, closed without merging